# -*- coding: utf-8 -*-
"""MediTrustAI mini

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19lAgfZqCld9u9Ie7waQUvS0Yp3yLg39q

Dependencies
"""

!pip install crewai
!pip install crewai_tools
!pip install langchain_community
!pip install faiss--cpu
!pip install crewai groq
!pip  install langchain_groq

# Commented out IPython magic to ensure Python compatibility.
# %run crew.py

"""To create a chain we need the following

1. Prompt
2. LLM
3. Docs

Preparing the docs
"""

from langchain_community.document_loaders import TextLoader
docs_1=TextLoader("/content/blood_test_report.md")
docs_1=docs_1.load()
docs_2=TextLoader("/content/advise.md")
docs_2=docs_2.load()
from langchain.text_splitter import RecursiveCharacterTextSplitter
rcts=RecursiveCharacterTextSplitter(chunk_size=500,chunk_overlap=50)
docs_1=rcts.split_documents(docs_1)
docs_2=rcts.split_documents(docs_2)
docs=docs_1 + docs_2

docs

from langchain.prompts import ChatPromptTemplate, MessagesPlaceholder
prompt=ChatPromptTemplate.from_messages([
    ("system","You are MediTrust AI an AI bot for healthcare"),
    ("system","Answer user questions from the {context}"),
    ("user","{input}"),
    MessagesPlaceholder(variable_name="chat_history")
])

from google.colab import userdata
GROQ_API_KEY=userdata.get('GROQ_API_KEY')
import os
os.environ['GROQ_API_KEY']=GROQ_API_KEY

from langchain_groq import ChatGroq
llm=ChatGroq(model="llama-3.3-70b-versatile")

llm.invoke("hello")

from langchain.chains.combine_documents import create_stuff_documents_chain
doc_chain=create_stuff_documents_chain(llm,prompt)

"""Message History maintenance"""

class chat_history:
 def __init__(self):
  self.history_dict={}
  self.history_list=[]


 def add(self,user_input,bot_response):
    self.user_input=user_input
    self.bot_response=bot_response
    self.history_dict["user"]=self.user_input
    self.history_dict["bot"]=self.bot_response
    self.history_list.append(self.history_dict)

doc_chain.invoke({
    "context":docs,
    "chat_history":[],
    "input":"summarize my report"
})

"""MediTrustAI Bot"""

history=chat_history()

def MediTrustAI_bot(user_input):
  result=doc_chain.invoke({
      "context":docs,
      "input":user_input,
      "chat_history":history.history_list
  })
  history.add(user_input,result)
  return result

history.history_list

MediTrustAI_bot("hi")

